---
version: "3.7"

networks:
  http_dev:
    external: true


secrets:
  config_json:
    file: ./src/secrets/config.json
  admin_fullchain_pem:
    file: ./src/secrets/admin_fullchain.pem
  admin_privkey_pem:
    file: ./src/secrets/admin_privkey.pem
  phish_fullchain_pem:
    file: ./src/secrets/phish_fullchain.pem
  phish_privkey_pem:
    file: ./src/secrets/phish_privkey.pem

services:
  gophish:
    build:
      # Note build arguments here are for builds using docker-compose (pytest)
      # The CI build workflow uses docker and passes the value from bump_version
      args:
        - VERSION=0.0.8
      context: .
      dockerfile: Dockerfile
    image: cisagov/gophish
    init: true
    restart: always
    ports:
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
        protocol: tcp
        mode: host
    networks:
      - http_dev
    secrets:
      - source: config_json
        target: config.json
      - source: admin_fullchain_pem
        target: admin_fullchain.pem
      - source: admin_privkey_pem
        target: admin_privkey.pem
      - source: phish_fullchain_pem
        target: phish_fullchain.pem
      - source: phish_privkey_pem
        target: phish_privkey.pem
    deploy:
      labels:
        caddy: gophish.tool.vm
        caddy.tls: "/data/local-cert.pem /data/local-key.pem"
        caddy.reverse_proxy: "{{ upstreams 80 }}"
      resources:  
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 500M
